<a href="https://colab.research.google.com/github/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/blob/main/Rafeek_Colab_Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. resale-flat-prices-based-on-approval-date-2000-feb-2012_1

In [1]:
import pandas as pd

# Paste your copied Raw URL here
url = "https://raw.githubusercontent.com/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/refs/heads/main/resale-flat-prices-based-on-approval-date-2000-feb-2012_1.csv"

# Load the dataset directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
0,2000-01,ANG MO KIO,3 ROOM,170,ANG MO KIO AVE 4,07 TO 09,69.0,Improved,1986,147000.0
1,2000-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,04 TO 06,61.0,Improved,1986,144000.0
2,2000-01,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,07 TO 09,73.0,New Generation,1976,159000.0
3,2000-01,ANG MO KIO,3 ROOM,215,ANG MO KIO AVE 1,07 TO 09,73.0,New Generation,1976,167000.0
4,2000-01,ANG MO KIO,3 ROOM,218,ANG MO KIO AVE 1,07 TO 09,67.0,New Generation,1976,163000.0

1. resale-flat-prices-based-on-approval-date-2000-feb-2012_2

In [2]:
import pandas as pd

# Paste your copied Raw URL here
url = "https://raw.githubusercontent.com/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/refs/heads/main/resale-flat-prices-based-on-approval-date-2000-feb-2012_2.csv"

# Load the dataset directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows
df.head()

,2005-06,ANG MO KIO,3 ROOM,405,ANG MO KIO AVE 10,07 TO 09,67,New Generation,1979,151000
0,2005-06,ANG MO KIO,3 ROOM,441,ANG MO KIO AVE 10,10 TO 12,67.0,New Generation,1979,162750.0
1,2005-06,ANG MO KIO,3 ROOM,440,ANG MO KIO AVE 10,01 TO 03,67.0,New Generation,1979,125000.0
2,2005-06,ANG MO KIO,3 ROOM,442,ANG MO KIO AVE 10,04 TO 06,67.0,New Generation,1979,152000.0
3,2005-06,ANG MO KIO,3 ROOM,444,ANG MO KIO AVE 10,01 TO 03,67.0,New Generation,1979,125000.0
4,2005-06,ANG MO KIO,3 ROOM,474,ANG MO KIO AVE 10,07 TO 09,81.0,New Generation,1984,206000.0

2. resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014

In [3]:
import pandas as pd

# Paste your copied Raw URL here
url = "https://raw.githubusercontent.com/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/refs/heads/main/resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014.csv"

# Load the dataset directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
0,2012-03,ANG MO KIO,2 ROOM,172,ANG MO KIO AVE 4,06 TO 10,45.0,Improved,1986,250000.0
1,2012-03,ANG MO KIO,2 ROOM,510,ANG MO KIO AVE 8,01 TO 05,44.0,Improved,1980,265000.0
2,2012-03,ANG MO KIO,3 ROOM,610,ANG MO KIO AVE 4,06 TO 10,68.0,New Generation,1980,315000.0
3,2012-03,ANG MO KIO,3 ROOM,474,ANG MO KIO AVE 10,01 TO 05,67.0,New Generation,1984,320000.0
4,2012-03,ANG MO KIO,3 ROOM,604,ANG MO KIO AVE 5,06 TO 10,67.0,New Generation,1980,321000.0

3.
resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016

In [4]:
import pandas as pd

# Paste your copied Raw URL here
url = "https://raw.githubusercontent.com/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/refs/heads/main/resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016.csv"


# Load the dataset directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2015-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,07 TO 09,60.0,Improved,1986,70,255000.0
1,2015-01,ANG MO KIO,3 ROOM,541,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1981,65,275000.0
2,2015-01,ANG MO KIO,3 ROOM,163,ANG MO KIO AVE 4,01 TO 03,69.0,New Generation,1980,64,285000.0
3,2015-01,ANG MO KIO,3 ROOM,446,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1979,63,290000.0
4,2015-01,ANG MO KIO,3 ROOM,557,ANG MO KIO AVE 10,07 TO 09,68.0,New Generation,1980,64,290000.0

4. ResaleflatpricesbasedonregistrationdatefromJan2017onwards

In [5]:
import pandas as pd

# Paste your copied Raw URL here
url = "https://raw.githubusercontent.com/Rafeek-Data/Rafeek-Ahamed_Capstone-Project/refs/heads/main/ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv"

# Load the dataset directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0